version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DISCORD_TOKEN=ODY4NjYxNTExNzQzMjM4MTQ1.YPy6Ew.fTDRGZ3_aVotj0zR8kCtAaGT5u0
