name: Build and Deploy
on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t kzdv/mcp .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub (Master)
        if: contains(github.ref, 'master')
        run: |
          docker tag kzdv/mcp kzdv/mcp:latest
          docker push kzdv/mcp:latest
          
      - name: Push to Docker Hub (Dev)
        if: contains(github.ref, 'dev')
        run: |
          docker tag kzdv/mcp kzdv/mcp:dev
          docker push kzdv/mcp:dev

      - name: Deploy to Kubernetes Cluster
        if: contains(github.ref, 'master')
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment/mcp -n prod

      - name: Verify deployment
        if: contains(github.ref, 'master')
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment/mcp -n prod