name: Build
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

env:
  SERVICE_NAME: bot

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set sha_short
        id: vars
        run: |-
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          # Set default branch name for PRs, as we still want to test build an image on PRs
          # but we have no branch to set a tag for.
          branch="test"
          if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
            branch="${GITHUB_REF#refs/heads/}"
          fi
          echo "branch=${branch}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.branch }}
      - name: Push Docker Image
        if: ${{ github.event_name == 'push' }}
        run: |-
          docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE_NAME:${{ env.branch }}